#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 56
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_root_project_icon = 1,
  sym_child_project_icon = 2,
  sym_grandchild_project_icon = 3,
  sym_great_grandchild_project_icon = 4,
  sym_leaf_project_icon = 5,
  sym_comment_icon = 6,
  sym_section_icon = 7,
  sym_id_start = 8,
  sym_id_number = 9,
  sym_text = 10,
  sym_new_line = 11,
  sym_source_file = 12,
  sym_root_project = 13,
  sym_child_project = 14,
  sym_grandchild_project = 15,
  sym_great_grandchild_project = 16,
  sym_leaf_project = 17,
  sym_comment = 18,
  sym_section = 19,
  sym_id = 20,
  aux_sym_source_file_repeat1 = 21,
  aux_sym_root_project_repeat1 = 22,
  aux_sym_root_project_repeat2 = 23,
  aux_sym_root_project_repeat3 = 24,
  aux_sym_child_project_repeat1 = 25,
  aux_sym_grandchild_project_repeat1 = 26,
  aux_sym_great_grandchild_project_repeat1 = 27,
  aux_sym_comment_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_root_project_icon] = "root_project_icon",
  [sym_child_project_icon] = "child_project_icon",
  [sym_grandchild_project_icon] = "grandchild_project_icon",
  [sym_great_grandchild_project_icon] = "great_grandchild_project_icon",
  [sym_leaf_project_icon] = "leaf_project_icon",
  [sym_comment_icon] = "comment_icon",
  [sym_section_icon] = "section_icon",
  [sym_id_start] = "id_start",
  [sym_id_number] = "id_number",
  [sym_text] = "text",
  [sym_new_line] = "new_line",
  [sym_source_file] = "source_file",
  [sym_root_project] = "root_project",
  [sym_child_project] = "child_project",
  [sym_grandchild_project] = "grandchild_project",
  [sym_great_grandchild_project] = "great_grandchild_project",
  [sym_leaf_project] = "leaf_project",
  [sym_comment] = "comment",
  [sym_section] = "section",
  [sym_id] = "id",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_root_project_repeat1] = "root_project_repeat1",
  [aux_sym_root_project_repeat2] = "root_project_repeat2",
  [aux_sym_root_project_repeat3] = "root_project_repeat3",
  [aux_sym_child_project_repeat1] = "child_project_repeat1",
  [aux_sym_grandchild_project_repeat1] = "grandchild_project_repeat1",
  [aux_sym_great_grandchild_project_repeat1] = "great_grandchild_project_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_root_project_icon] = sym_root_project_icon,
  [sym_child_project_icon] = sym_child_project_icon,
  [sym_grandchild_project_icon] = sym_grandchild_project_icon,
  [sym_great_grandchild_project_icon] = sym_great_grandchild_project_icon,
  [sym_leaf_project_icon] = sym_leaf_project_icon,
  [sym_comment_icon] = sym_comment_icon,
  [sym_section_icon] = sym_section_icon,
  [sym_id_start] = sym_id_start,
  [sym_id_number] = sym_id_number,
  [sym_text] = sym_text,
  [sym_new_line] = sym_new_line,
  [sym_source_file] = sym_source_file,
  [sym_root_project] = sym_root_project,
  [sym_child_project] = sym_child_project,
  [sym_grandchild_project] = sym_grandchild_project,
  [sym_great_grandchild_project] = sym_great_grandchild_project,
  [sym_leaf_project] = sym_leaf_project,
  [sym_comment] = sym_comment,
  [sym_section] = sym_section,
  [sym_id] = sym_id,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_root_project_repeat1] = aux_sym_root_project_repeat1,
  [aux_sym_root_project_repeat2] = aux_sym_root_project_repeat2,
  [aux_sym_root_project_repeat3] = aux_sym_root_project_repeat3,
  [aux_sym_child_project_repeat1] = aux_sym_child_project_repeat1,
  [aux_sym_grandchild_project_repeat1] = aux_sym_grandchild_project_repeat1,
  [aux_sym_great_grandchild_project_repeat1] = aux_sym_great_grandchild_project_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_root_project_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_child_project_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_grandchild_project_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_great_grandchild_project_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_project_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_section_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_id_start] = {
    .visible = true,
    .named = true,
  },
  [sym_id_number] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_new_line] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_root_project] = {
    .visible = true,
    .named = true,
  },
  [sym_child_project] = {
    .visible = true,
    .named = true,
  },
  [sym_grandchild_project] = {
    .visible = true,
    .named = true,
  },
  [sym_great_grandchild_project] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_project] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_root_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_root_project_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_root_project_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_child_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_grandchild_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_great_grandchild_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '#') ADVANCE(2);
      if (lookahead == '+') ADVANCE(3);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '|') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1)
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '+' &&
          lookahead != '/' &&
          lookahead != '|') ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(13);
      if (lookahead == '#') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(14);
      if (lookahead == '#') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(15);
      if (lookahead == '#') ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == ' ') ADVANCE(16);
      if (lookahead == '#') ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == ' ') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(6);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '#') ADVANCE(2);
      if (lookahead == '+') ADVANCE(3);
      if (lookahead == '/') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '|') ADVANCE(24);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_root_project_icon);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_child_project_icon);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_grandchild_project_icon);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_great_grandchild_project_icon);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_leaf_project_icon);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_comment_icon);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_section_icon);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_id_start);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_id_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '+' &&
          lookahead != '/' &&
          lookahead != '|') ADVANCE(24);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          (11 <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '+' &&
          lookahead != '/' &&
          lookahead != '|') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '+' &&
          lookahead != '/' &&
          lookahead != '|') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_new_line);
      if (lookahead == '\n') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 11},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 11},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 11},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_root_project_icon] = ACTIONS(1),
    [sym_child_project_icon] = ACTIONS(1),
    [sym_grandchild_project_icon] = ACTIONS(1),
    [sym_great_grandchild_project_icon] = ACTIONS(1),
    [sym_leaf_project_icon] = ACTIONS(1),
    [sym_comment_icon] = ACTIONS(1),
    [sym_section_icon] = ACTIONS(1),
    [sym_id_start] = ACTIONS(1),
    [sym_id_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(55),
    [sym_root_project] = STATE(45),
    [aux_sym_source_file_repeat1] = STATE(45),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_root_project_icon] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(9), 1,
      sym_leaf_project_icon,
    ACTIONS(11), 1,
      sym_comment_icon,
    ACTIONS(13), 1,
      sym_section_icon,
    STATE(3), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(10), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(29), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(7), 5,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [29] = 7,
    ACTIONS(9), 1,
      sym_leaf_project_icon,
    ACTIONS(11), 1,
      sym_comment_icon,
    ACTIONS(13), 1,
      sym_section_icon,
    STATE(13), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(17), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(24), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(15), 5,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [58] = 7,
    ACTIONS(11), 1,
      sym_comment_icon,
    ACTIONS(13), 1,
      sym_section_icon,
    ACTIONS(19), 1,
      sym_great_grandchild_project_icon,
    STATE(5), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(16), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(34), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(17), 4,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [86] = 7,
    ACTIONS(11), 1,
      sym_comment_icon,
    ACTIONS(13), 1,
      sym_section_icon,
    ACTIONS(19), 1,
      sym_great_grandchild_project_icon,
    STATE(17), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(19), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(33), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(21), 4,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [114] = 5,
    ACTIONS(11), 1,
      sym_comment_icon,
    ACTIONS(13), 1,
      sym_section_icon,
    STATE(8), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(22), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    ACTIONS(23), 6,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
      sym_leaf_project_icon,
  [137] = 7,
    ACTIONS(11), 1,
      sym_comment_icon,
    ACTIONS(13), 1,
      sym_section_icon,
    ACTIONS(27), 1,
      sym_grandchild_project_icon,
    STATE(17), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(23), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(37), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
    ACTIONS(25), 3,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
  [164] = 5,
    ACTIONS(11), 1,
      sym_comment_icon,
    ACTIONS(13), 1,
      sym_section_icon,
    STATE(18), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(21), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    ACTIONS(29), 6,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
      sym_leaf_project_icon,
  [187] = 7,
    ACTIONS(11), 1,
      sym_comment_icon,
    ACTIONS(13), 1,
      sym_section_icon,
    ACTIONS(27), 1,
      sym_grandchild_project_icon,
    STATE(7), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(20), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(35), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
    ACTIONS(31), 3,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
  [214] = 5,
    ACTIONS(9), 1,
      sym_leaf_project_icon,
    ACTIONS(13), 1,
      sym_section_icon,
    STATE(18), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(24), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(15), 5,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [236] = 4,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      aux_sym_comment_repeat1,
    ACTIONS(37), 2,
      sym_text,
      sym_new_line,
    ACTIONS(35), 7,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
      sym_leaf_project_icon,
      sym_comment_icon,
      sym_section_icon,
  [256] = 7,
    ACTIONS(11), 1,
      sym_comment_icon,
    ACTIONS(13), 1,
      sym_section_icon,
    ACTIONS(42), 1,
      sym_child_project_icon,
    ACTIONS(40), 2,
      ts_builtin_sym_end,
      sym_root_project_icon,
    STATE(17), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(26), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(39), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [282] = 5,
    ACTIONS(9), 1,
      sym_leaf_project_icon,
    ACTIONS(13), 1,
      sym_section_icon,
    STATE(18), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(27), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(44), 5,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [304] = 4,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      aux_sym_comment_repeat1,
    ACTIONS(50), 2,
      sym_text,
      sym_new_line,
    ACTIONS(48), 7,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
      sym_leaf_project_icon,
      sym_comment_icon,
      sym_section_icon,
  [324] = 7,
    ACTIONS(11), 1,
      sym_comment_icon,
    ACTIONS(13), 1,
      sym_section_icon,
    ACTIONS(42), 1,
      sym_child_project_icon,
    ACTIONS(52), 2,
      ts_builtin_sym_end,
      sym_root_project_icon,
    STATE(12), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(28), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(41), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [350] = 5,
    ACTIONS(13), 1,
      sym_section_icon,
    ACTIONS(19), 1,
      sym_great_grandchild_project_icon,
    STATE(18), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(33), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(21), 4,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [371] = 3,
    ACTIONS(56), 1,
      sym_comment_icon,
    STATE(17), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    ACTIONS(54), 7,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
      sym_leaf_project_icon,
      sym_section_icon,
  [388] = 3,
    ACTIONS(61), 1,
      sym_section_icon,
    STATE(18), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    ACTIONS(59), 7,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
      sym_leaf_project_icon,
      sym_comment_icon,
  [405] = 5,
    ACTIONS(13), 1,
      sym_section_icon,
    ACTIONS(19), 1,
      sym_great_grandchild_project_icon,
    STATE(18), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(32), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(64), 4,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [426] = 5,
    ACTIONS(13), 1,
      sym_section_icon,
    ACTIONS(27), 1,
      sym_grandchild_project_icon,
    STATE(18), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(37), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
    ACTIONS(25), 3,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
  [446] = 3,
    ACTIONS(11), 1,
      sym_comment_icon,
    STATE(17), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    ACTIONS(66), 6,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
      sym_leaf_project_icon,
  [462] = 3,
    ACTIONS(11), 1,
      sym_comment_icon,
    STATE(17), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    ACTIONS(29), 6,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
      sym_leaf_project_icon,
  [478] = 5,
    ACTIONS(13), 1,
      sym_section_icon,
    ACTIONS(27), 1,
      sym_grandchild_project_icon,
    STATE(18), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(38), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
    ACTIONS(68), 3,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
  [498] = 3,
    ACTIONS(9), 1,
      sym_leaf_project_icon,
    STATE(30), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(44), 5,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [513] = 1,
    ACTIONS(70), 8,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
      sym_leaf_project_icon,
      sym_comment_icon,
      sym_section_icon,
  [524] = 5,
    ACTIONS(13), 1,
      sym_section_icon,
    ACTIONS(42), 1,
      sym_child_project_icon,
    ACTIONS(72), 2,
      ts_builtin_sym_end,
      sym_root_project_icon,
    STATE(18), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(42), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [543] = 3,
    ACTIONS(9), 1,
      sym_leaf_project_icon,
    STATE(30), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(74), 5,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [558] = 5,
    ACTIONS(13), 1,
      sym_section_icon,
    ACTIONS(42), 1,
      sym_child_project_icon,
    ACTIONS(40), 2,
      ts_builtin_sym_end,
      sym_root_project_icon,
    STATE(18), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(39), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [577] = 3,
    ACTIONS(9), 1,
      sym_leaf_project_icon,
    STATE(30), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(15), 5,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [592] = 3,
    ACTIONS(78), 1,
      sym_leaf_project_icon,
    STATE(30), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(76), 5,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [607] = 3,
    ACTIONS(83), 1,
      sym_great_grandchild_project_icon,
    STATE(31), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(81), 4,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [621] = 3,
    ACTIONS(19), 1,
      sym_great_grandchild_project_icon,
    STATE(31), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(86), 4,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [635] = 3,
    ACTIONS(19), 1,
      sym_great_grandchild_project_icon,
    STATE(31), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(64), 4,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [649] = 3,
    ACTIONS(19), 1,
      sym_great_grandchild_project_icon,
    STATE(31), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(21), 4,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [663] = 3,
    ACTIONS(27), 1,
      sym_grandchild_project_icon,
    STATE(36), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
    ACTIONS(25), 3,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
  [676] = 3,
    ACTIONS(90), 1,
      sym_grandchild_project_icon,
    STATE(36), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
    ACTIONS(88), 3,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
  [689] = 3,
    ACTIONS(27), 1,
      sym_grandchild_project_icon,
    STATE(36), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
    ACTIONS(68), 3,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
  [702] = 3,
    ACTIONS(27), 1,
      sym_grandchild_project_icon,
    STATE(36), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
    ACTIONS(93), 3,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
  [715] = 3,
    ACTIONS(42), 1,
      sym_child_project_icon,
    ACTIONS(72), 2,
      ts_builtin_sym_end,
      sym_root_project_icon,
    STATE(40), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [727] = 3,
    ACTIONS(97), 1,
      sym_child_project_icon,
    ACTIONS(95), 2,
      ts_builtin_sym_end,
      sym_root_project_icon,
    STATE(40), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [739] = 3,
    ACTIONS(42), 1,
      sym_child_project_icon,
    ACTIONS(40), 2,
      ts_builtin_sym_end,
      sym_root_project_icon,
    STATE(40), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [751] = 3,
    ACTIONS(42), 1,
      sym_child_project_icon,
    ACTIONS(100), 2,
      ts_builtin_sym_end,
      sym_root_project_icon,
    STATE(40), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [763] = 1,
    ACTIONS(102), 5,
      ts_builtin_sym_end,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_comment_icon,
      sym_section_icon,
  [771] = 3,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(106), 1,
      sym_root_project_icon,
    STATE(44), 2,
      sym_root_project,
      aux_sym_source_file_repeat1,
  [782] = 3,
    ACTIONS(5), 1,
      sym_root_project_icon,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    STATE(44), 2,
      sym_root_project,
      aux_sym_source_file_repeat1,
  [793] = 2,
    STATE(14), 1,
      aux_sym_comment_repeat1,
    ACTIONS(111), 2,
      sym_text,
      sym_new_line,
  [801] = 2,
    ACTIONS(113), 1,
      sym_id_start,
    STATE(15), 1,
      sym_id,
  [808] = 1,
    ACTIONS(115), 1,
      sym_text,
  [812] = 1,
    ACTIONS(117), 1,
      sym_text,
  [816] = 1,
    ACTIONS(119), 1,
      sym_text,
  [820] = 1,
    ACTIONS(121), 1,
      sym_text,
  [824] = 1,
    ACTIONS(123), 1,
      sym_text,
  [828] = 1,
    ACTIONS(125), 1,
      sym_text,
  [832] = 1,
    ACTIONS(127), 1,
      sym_id_number,
  [836] = 1,
    ACTIONS(129), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 29,
  [SMALL_STATE(4)] = 58,
  [SMALL_STATE(5)] = 86,
  [SMALL_STATE(6)] = 114,
  [SMALL_STATE(7)] = 137,
  [SMALL_STATE(8)] = 164,
  [SMALL_STATE(9)] = 187,
  [SMALL_STATE(10)] = 214,
  [SMALL_STATE(11)] = 236,
  [SMALL_STATE(12)] = 256,
  [SMALL_STATE(13)] = 282,
  [SMALL_STATE(14)] = 304,
  [SMALL_STATE(15)] = 324,
  [SMALL_STATE(16)] = 350,
  [SMALL_STATE(17)] = 371,
  [SMALL_STATE(18)] = 388,
  [SMALL_STATE(19)] = 405,
  [SMALL_STATE(20)] = 426,
  [SMALL_STATE(21)] = 446,
  [SMALL_STATE(22)] = 462,
  [SMALL_STATE(23)] = 478,
  [SMALL_STATE(24)] = 498,
  [SMALL_STATE(25)] = 513,
  [SMALL_STATE(26)] = 524,
  [SMALL_STATE(27)] = 543,
  [SMALL_STATE(28)] = 558,
  [SMALL_STATE(29)] = 577,
  [SMALL_STATE(30)] = 592,
  [SMALL_STATE(31)] = 607,
  [SMALL_STATE(32)] = 621,
  [SMALL_STATE(33)] = 635,
  [SMALL_STATE(34)] = 649,
  [SMALL_STATE(35)] = 663,
  [SMALL_STATE(36)] = 676,
  [SMALL_STATE(37)] = 689,
  [SMALL_STATE(38)] = 702,
  [SMALL_STATE(39)] = 715,
  [SMALL_STATE(40)] = 727,
  [SMALL_STATE(41)] = 739,
  [SMALL_STATE(42)] = 751,
  [SMALL_STATE(43)] = 763,
  [SMALL_STATE(44)] = 771,
  [SMALL_STATE(45)] = 782,
  [SMALL_STATE(46)] = 793,
  [SMALL_STATE(47)] = 801,
  [SMALL_STATE(48)] = 808,
  [SMALL_STATE(49)] = 812,
  [SMALL_STATE(50)] = 816,
  [SMALL_STATE(51)] = 820,
  [SMALL_STATE(52)] = 824,
  [SMALL_STATE(53)] = 828,
  [SMALL_STATE(54)] = 832,
  [SMALL_STATE(55)] = 836,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 2),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_project, 2),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 3),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_project, 3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 2),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(11),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_project, 4),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 4),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_project, 3),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_root_project_repeat1, 2),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_root_project_repeat1, 2), SHIFT_REPEAT(46),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_root_project_repeat2, 2),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_root_project_repeat2, 2), SHIFT_REPEAT(52),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 4),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_project, 4),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 4),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_project, 5),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 5),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2), SHIFT_REPEAT(50),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_grandchild_project_repeat1, 2),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grandchild_project_repeat1, 2), SHIFT_REPEAT(49),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 5),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_child_project_repeat1, 2),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_child_project_repeat1, 2), SHIFT_REPEAT(48),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 5),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_root_project_repeat3, 2),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_root_project_repeat3, 2), SHIFT_REPEAT(53),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_project, 6),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id, 2),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(51),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [129] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_projects(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
