#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 91
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  sym_root_project_icon = 2,
  sym_child_project_icon = 3,
  sym_grandchild_project_icon = 4,
  sym_great_grandchild_project_icon = 5,
  sym_leaf_project_icon = 6,
  sym_comment_icon = 7,
  sym_section_icon = 8,
  anon_sym_PIPE_GT = 9,
  anon_sym_AT = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  sym_url_description = 15,
  sym_url = 16,
  sym_id_number = 17,
  aux_sym_text_line_token1 = 18,
  sym_escaped_left_bracket = 19,
  sym_escaped_right_bracket = 20,
  sym_escaped_left_parenthesis = 21,
  sym_escaped_right_parenthesis = 22,
  sym_escaped_at = 23,
  sym_source_file = 24,
  sym_root_project = 25,
  sym_child_project = 26,
  sym_grandchild_project = 27,
  sym_great_grandchild_project = 28,
  sym_leaf_project = 29,
  sym_comment = 30,
  sym_section = 31,
  sym_id = 32,
  sym_sync_token = 33,
  sym_markdown_url = 34,
  sym_text_line = 35,
  aux_sym_source_file_repeat1 = 36,
  aux_sym_root_project_repeat1 = 37,
  aux_sym_root_project_repeat2 = 38,
  aux_sym_root_project_repeat3 = 39,
  aux_sym_child_project_repeat1 = 40,
  aux_sym_grandchild_project_repeat1 = 41,
  aux_sym_great_grandchild_project_repeat1 = 42,
  aux_sym_comment_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym_root_project_icon] = "root_project_icon",
  [sym_child_project_icon] = "child_project_icon",
  [sym_grandchild_project_icon] = "grandchild_project_icon",
  [sym_great_grandchild_project_icon] = "great_grandchild_project_icon",
  [sym_leaf_project_icon] = "leaf_project_icon",
  [sym_comment_icon] = "comment_icon",
  [sym_section_icon] = "section_icon",
  [anon_sym_PIPE_GT] = "|>",
  [anon_sym_AT] = "@",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_url_description] = "url_description",
  [sym_url] = "url",
  [sym_id_number] = "id_number",
  [aux_sym_text_line_token1] = "text_line_token1",
  [sym_escaped_left_bracket] = "escaped_left_bracket",
  [sym_escaped_right_bracket] = "escaped_right_bracket",
  [sym_escaped_left_parenthesis] = "escaped_left_parenthesis",
  [sym_escaped_right_parenthesis] = "escaped_right_parenthesis",
  [sym_escaped_at] = "escaped_at",
  [sym_source_file] = "source_file",
  [sym_root_project] = "root_project",
  [sym_child_project] = "child_project",
  [sym_grandchild_project] = "grandchild_project",
  [sym_great_grandchild_project] = "great_grandchild_project",
  [sym_leaf_project] = "leaf_project",
  [sym_comment] = "comment",
  [sym_section] = "section",
  [sym_id] = "id",
  [sym_sync_token] = "sync_token",
  [sym_markdown_url] = "markdown_url",
  [sym_text_line] = "text_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_root_project_repeat1] = "root_project_repeat1",
  [aux_sym_root_project_repeat2] = "root_project_repeat2",
  [aux_sym_root_project_repeat3] = "root_project_repeat3",
  [aux_sym_child_project_repeat1] = "child_project_repeat1",
  [aux_sym_grandchild_project_repeat1] = "grandchild_project_repeat1",
  [aux_sym_great_grandchild_project_repeat1] = "great_grandchild_project_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym_root_project_icon] = sym_root_project_icon,
  [sym_child_project_icon] = sym_child_project_icon,
  [sym_grandchild_project_icon] = sym_grandchild_project_icon,
  [sym_great_grandchild_project_icon] = sym_great_grandchild_project_icon,
  [sym_leaf_project_icon] = sym_leaf_project_icon,
  [sym_comment_icon] = sym_comment_icon,
  [sym_section_icon] = sym_section_icon,
  [anon_sym_PIPE_GT] = anon_sym_PIPE_GT,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_url_description] = sym_url_description,
  [sym_url] = sym_url,
  [sym_id_number] = sym_id_number,
  [aux_sym_text_line_token1] = aux_sym_text_line_token1,
  [sym_escaped_left_bracket] = sym_escaped_left_bracket,
  [sym_escaped_right_bracket] = sym_escaped_right_bracket,
  [sym_escaped_left_parenthesis] = sym_escaped_left_parenthesis,
  [sym_escaped_right_parenthesis] = sym_escaped_right_parenthesis,
  [sym_escaped_at] = sym_escaped_at,
  [sym_source_file] = sym_source_file,
  [sym_root_project] = sym_root_project,
  [sym_child_project] = sym_child_project,
  [sym_grandchild_project] = sym_grandchild_project,
  [sym_great_grandchild_project] = sym_great_grandchild_project,
  [sym_leaf_project] = sym_leaf_project,
  [sym_comment] = sym_comment,
  [sym_section] = sym_section,
  [sym_id] = sym_id,
  [sym_sync_token] = sym_sync_token,
  [sym_markdown_url] = sym_markdown_url,
  [sym_text_line] = sym_text_line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_root_project_repeat1] = aux_sym_root_project_repeat1,
  [aux_sym_root_project_repeat2] = aux_sym_root_project_repeat2,
  [aux_sym_root_project_repeat3] = aux_sym_root_project_repeat3,
  [aux_sym_child_project_repeat1] = aux_sym_child_project_repeat1,
  [aux_sym_grandchild_project_repeat1] = aux_sym_grandchild_project_repeat1,
  [aux_sym_great_grandchild_project_repeat1] = aux_sym_great_grandchild_project_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_root_project_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_child_project_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_grandchild_project_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_great_grandchild_project_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_project_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_section_icon] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_url_description] = {
    .visible = true,
    .named = true,
  },
  [sym_url] = {
    .visible = true,
    .named = true,
  },
  [sym_id_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_text_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escaped_left_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_escaped_right_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_escaped_left_parenthesis] = {
    .visible = true,
    .named = true,
  },
  [sym_escaped_right_parenthesis] = {
    .visible = true,
    .named = true,
  },
  [sym_escaped_at] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_root_project] = {
    .visible = true,
    .named = true,
  },
  [sym_child_project] = {
    .visible = true,
    .named = true,
  },
  [sym_grandchild_project] = {
    .visible = true,
    .named = true,
  },
  [sym_great_grandchild_project] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_project] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym_sync_token] = {
    .visible = true,
    .named = true,
  },
  [sym_markdown_url] = {
    .visible = true,
    .named = true,
  },
  [sym_text_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_root_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_root_project_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_root_project_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_child_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_grandchild_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_great_grandchild_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 5,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 5,
  [90] = 90,
};

static inline bool aux_sym_text_line_token1_character_set_1(int32_t c) {
  return (c < '+'
    ? (c < '&'
      ? (c < '#'
        ? c == 0
        : c <= '#')
      : (c <= '&' || (c >= '(' && c <= ')')))
    : (c <= '+' || (c < '['
      ? (c < '@'
        ? c == '>'
        : c <= '@')
      : (c <= ']' || c == '|'))));
}

static inline bool aux_sym_text_line_token1_character_set_2(int32_t c) {
  return (c < '+'
    ? (c < '#'
      ? (c < '\n'
        ? c == 0
        : c <= '\n')
      : (c <= '#' || (c < '('
        ? c == '&'
        : c <= ')')))
    : (c <= '+' || (c < '['
      ? (c < '@'
        ? c == '>'
        : c <= '@')
      : (c <= ']' || c == '|'))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == '&') ADVANCE(23);
      if (lookahead == '(') ADVANCE(28);
      if (lookahead == ')') ADVANCE(29);
      if (lookahead == '+') ADVANCE(22);
      if (lookahead == '@') ADVANCE(25);
      if (lookahead == '[') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == ']') ADVANCE(27);
      if (lookahead == 'h') ADVANCE(11);
      if (lookahead == '|') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == '&') ADVANCE(23);
      if (lookahead == '(') ADVANCE(28);
      if (lookahead == '+') ADVANCE(22);
      if (lookahead == '@') ADVANCE(25);
      if (lookahead == '[') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == '|') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '>' &&
          lookahead != ']') ADVANCE(36);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2)
      if (lookahead == '\\') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (!aux_sym_text_line_token1_character_set_1(lookahead)) ADVANCE(36);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == ')') ADVANCE(40);
      if (lookahead == '@') ADVANCE(41);
      if (lookahead == '[') ADVANCE(37);
      if (lookahead == ']') ADVANCE(38);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(5);
      if (lookahead == 's') ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(24);
      END_STATE();
    case 9:
      if (lookahead == 'p') ADVANCE(7);
      END_STATE();
    case 10:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 12:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(31);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(14);
      END_STATE();
    case 14:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_root_project_icon);
      if (lookahead == '#') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_child_project_icon);
      if (lookahead == '#') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_grandchild_project_icon);
      if (lookahead == '#') ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_great_grandchild_project_icon);
      if (lookahead == '#') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_leaf_project_icon);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_comment_icon);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_section_icon);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_PIPE_GT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_url_description);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_url_description);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_url);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_id_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == '\n') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (!aux_sym_text_line_token1_character_set_1(lookahead)) ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == '\t' ||
          (11 <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (!aux_sym_text_line_token1_character_set_2(lookahead)) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (!aux_sym_text_line_token1_character_set_2(lookahead)) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_escaped_left_bracket);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_escaped_right_bracket);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_escaped_left_parenthesis);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_escaped_right_parenthesis);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_escaped_at);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 12},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_root_project_icon] = ACTIONS(1),
    [sym_child_project_icon] = ACTIONS(1),
    [sym_grandchild_project_icon] = ACTIONS(1),
    [sym_great_grandchild_project_icon] = ACTIONS(1),
    [sym_leaf_project_icon] = ACTIONS(1),
    [sym_comment_icon] = ACTIONS(1),
    [sym_section_icon] = ACTIONS(1),
    [anon_sym_PIPE_GT] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_url] = ACTIONS(1),
    [sym_id_number] = ACTIONS(1),
    [sym_escaped_left_bracket] = ACTIONS(1),
    [sym_escaped_right_bracket] = ACTIONS(1),
    [sym_escaped_left_parenthesis] = ACTIONS(1),
    [sym_escaped_right_parenthesis] = ACTIONS(1),
    [sym_escaped_at] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(90),
    [sym_root_project] = STATE(76),
    [aux_sym_source_file_repeat1] = STATE(76),
    [sym_root_project_icon] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(5), 1,
      anon_sym_LF,
    ACTIONS(9), 1,
      anon_sym_PIPE_GT,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    STATE(46), 1,
      sym_id,
    STATE(3), 3,
      sym_markdown_url,
      sym_text_line,
      aux_sym_comment_repeat1,
    ACTIONS(15), 6,
      aux_sym_text_line_token1,
      sym_escaped_left_bracket,
      sym_escaped_right_bracket,
      sym_escaped_left_parenthesis,
      sym_escaped_right_parenthesis,
      sym_escaped_at,
    ACTIONS(7), 8,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
      sym_leaf_project_icon,
      sym_comment_icon,
      sym_section_icon,
      anon_sym_AT,
  [39] = 6,
    ACTIONS(17), 1,
      anon_sym_LF,
    ACTIONS(22), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    STATE(3), 3,
      sym_markdown_url,
      sym_text_line,
      aux_sym_comment_repeat1,
    ACTIONS(28), 6,
      aux_sym_text_line_token1,
      sym_escaped_left_bracket,
      sym_escaped_right_bracket,
      sym_escaped_left_parenthesis,
      sym_escaped_right_parenthesis,
      sym_escaped_at,
    ACTIONS(20), 9,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
      sym_leaf_project_icon,
      sym_comment_icon,
      sym_section_icon,
      anon_sym_PIPE_GT,
      anon_sym_AT,
  [73] = 1,
    ACTIONS(31), 18,
      anon_sym_LF,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
      sym_leaf_project_icon,
      sym_comment_icon,
      sym_section_icon,
      anon_sym_PIPE_GT,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      aux_sym_text_line_token1,
      sym_escaped_left_bracket,
      sym_escaped_right_bracket,
      sym_escaped_left_parenthesis,
      sym_escaped_right_parenthesis,
      sym_escaped_at,
  [94] = 1,
    ACTIONS(33), 18,
      anon_sym_LF,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
      sym_leaf_project_icon,
      sym_comment_icon,
      sym_section_icon,
      anon_sym_PIPE_GT,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      aux_sym_text_line_token1,
      sym_escaped_left_bracket,
      sym_escaped_right_bracket,
      sym_escaped_left_parenthesis,
      sym_escaped_right_parenthesis,
      sym_escaped_at,
  [115] = 1,
    ACTIONS(35), 18,
      anon_sym_LF,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
      sym_leaf_project_icon,
      sym_comment_icon,
      sym_section_icon,
      anon_sym_PIPE_GT,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      aux_sym_text_line_token1,
      sym_escaped_left_bracket,
      sym_escaped_right_bracket,
      sym_escaped_left_parenthesis,
      sym_escaped_right_parenthesis,
      sym_escaped_at,
  [136] = 10,
    ACTIONS(39), 1,
      sym_leaf_project_icon,
    ACTIONS(41), 1,
      sym_comment_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(45), 1,
      anon_sym_PIPE_GT,
    ACTIONS(47), 1,
      anon_sym_AT,
    STATE(9), 1,
      sym_id,
    STATE(12), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(28), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(52), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(37), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [173] = 10,
    ACTIONS(41), 1,
      sym_comment_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(45), 1,
      anon_sym_PIPE_GT,
    ACTIONS(51), 1,
      sym_great_grandchild_project_icon,
    ACTIONS(53), 1,
      anon_sym_AT,
    STATE(14), 1,
      sym_id,
    STATE(17), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(31), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(58), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(49), 3,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [209] = 8,
    ACTIONS(39), 1,
      sym_leaf_project_icon,
    ACTIONS(41), 1,
      sym_comment_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(57), 1,
      anon_sym_AT,
    STATE(10), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(25), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(50), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(55), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [240] = 8,
    ACTIONS(39), 1,
      sym_leaf_project_icon,
    ACTIONS(41), 1,
      sym_comment_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(61), 1,
      anon_sym_AT,
    STATE(27), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(33), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(47), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(59), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [271] = 8,
    ACTIONS(41), 1,
      sym_comment_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(45), 1,
      anon_sym_PIPE_GT,
    STATE(22), 1,
      sym_id,
    ACTIONS(65), 2,
      sym_leaf_project_icon,
      anon_sym_AT,
    STATE(23), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(41), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    ACTIONS(63), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [302] = 8,
    ACTIONS(39), 1,
      sym_leaf_project_icon,
    ACTIONS(41), 1,
      sym_comment_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(57), 1,
      anon_sym_AT,
    STATE(25), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(33), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(50), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(55), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [333] = 10,
    ACTIONS(41), 1,
      sym_comment_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(45), 1,
      anon_sym_PIPE_GT,
    ACTIONS(69), 1,
      sym_grandchild_project_icon,
    ACTIONS(71), 1,
      anon_sym_AT,
    STATE(20), 1,
      sym_id,
    ACTIONS(67), 2,
      sym_root_project_icon,
      sym_child_project_icon,
    STATE(19), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(36), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(69), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
  [368] = 8,
    ACTIONS(41), 1,
      sym_comment_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(51), 1,
      sym_great_grandchild_project_icon,
    ACTIONS(75), 1,
      anon_sym_AT,
    STATE(15), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(32), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(62), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(73), 3,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [398] = 8,
    ACTIONS(41), 1,
      sym_comment_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(51), 1,
      sym_great_grandchild_project_icon,
    ACTIONS(79), 1,
      anon_sym_AT,
    STATE(33), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(34), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(55), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(77), 3,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [428] = 10,
    ACTIONS(41), 1,
      sym_comment_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(45), 1,
      anon_sym_PIPE_GT,
    ACTIONS(81), 1,
      sym_root_project_icon,
    ACTIONS(83), 1,
      sym_child_project_icon,
    ACTIONS(85), 1,
      anon_sym_AT,
    STATE(30), 1,
      sym_id,
    STATE(29), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(51), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(72), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [462] = 8,
    ACTIONS(41), 1,
      sym_comment_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(51), 1,
      sym_great_grandchild_project_icon,
    ACTIONS(75), 1,
      anon_sym_AT,
    STATE(32), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(33), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(62), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(73), 3,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [492] = 5,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(87), 1,
      anon_sym_LF,
    STATE(2), 3,
      sym_markdown_url,
      sym_text_line,
      aux_sym_comment_repeat1,
    ACTIONS(15), 6,
      aux_sym_text_line_token1,
      sym_escaped_left_bracket,
      sym_escaped_right_bracket,
      sym_escaped_left_parenthesis,
      sym_escaped_right_parenthesis,
      sym_escaped_at,
  [515] = 8,
    ACTIONS(41), 1,
      sym_comment_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(69), 1,
      sym_grandchild_project_icon,
    ACTIONS(91), 1,
      anon_sym_AT,
    ACTIONS(89), 2,
      sym_root_project_icon,
      sym_child_project_icon,
    STATE(33), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(40), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(71), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
  [544] = 8,
    ACTIONS(41), 1,
      sym_comment_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(69), 1,
      sym_grandchild_project_icon,
    ACTIONS(91), 1,
      anon_sym_AT,
    ACTIONS(89), 2,
      sym_root_project_icon,
      sym_child_project_icon,
    STATE(24), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(40), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(71), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
  [573] = 6,
    ACTIONS(41), 1,
      sym_comment_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(95), 2,
      sym_leaf_project_icon,
      anon_sym_AT,
    STATE(33), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(37), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    ACTIONS(93), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [598] = 6,
    ACTIONS(41), 1,
      sym_comment_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(99), 2,
      sym_leaf_project_icon,
      anon_sym_AT,
    STATE(21), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(38), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    ACTIONS(97), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [623] = 6,
    ACTIONS(41), 1,
      sym_comment_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(99), 2,
      sym_leaf_project_icon,
      anon_sym_AT,
    STATE(33), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(38), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    ACTIONS(97), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [648] = 8,
    ACTIONS(41), 1,
      sym_comment_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(69), 1,
      sym_grandchild_project_icon,
    ACTIONS(103), 1,
      anon_sym_AT,
    ACTIONS(101), 2,
      sym_root_project_icon,
      sym_child_project_icon,
    STATE(33), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(42), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(68), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
  [677] = 6,
    ACTIONS(39), 1,
      sym_leaf_project_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(61), 1,
      anon_sym_AT,
    STATE(43), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(47), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(59), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [701] = 8,
    ACTIONS(41), 1,
      sym_comment_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(83), 1,
      sym_child_project_icon,
    ACTIONS(105), 1,
      sym_root_project_icon,
    ACTIONS(107), 1,
      anon_sym_AT,
    STATE(33), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(48), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(77), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [729] = 6,
    ACTIONS(39), 1,
      sym_leaf_project_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(111), 1,
      anon_sym_AT,
    STATE(43), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(45), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(109), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [753] = 6,
    ACTIONS(39), 1,
      sym_leaf_project_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(57), 1,
      anon_sym_AT,
    STATE(43), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(50), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(55), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [777] = 8,
    ACTIONS(41), 1,
      sym_comment_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(83), 1,
      sym_child_project_icon,
    ACTIONS(113), 1,
      sym_root_project_icon,
    ACTIONS(115), 1,
      anon_sym_AT,
    STATE(33), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(44), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(75), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [805] = 8,
    ACTIONS(41), 1,
      sym_comment_icon,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(83), 1,
      sym_child_project_icon,
    ACTIONS(113), 1,
      sym_root_project_icon,
    ACTIONS(115), 1,
      anon_sym_AT,
    STATE(26), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(44), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(75), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [833] = 6,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(51), 1,
      sym_great_grandchild_project_icon,
    ACTIONS(75), 1,
      anon_sym_AT,
    STATE(43), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(62), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(73), 3,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [856] = 6,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(51), 1,
      sym_great_grandchild_project_icon,
    ACTIONS(79), 1,
      anon_sym_AT,
    STATE(43), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(55), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(77), 3,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [879] = 4,
    ACTIONS(121), 1,
      sym_comment_icon,
    STATE(33), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    ACTIONS(119), 3,
      sym_leaf_project_icon,
      sym_section_icon,
      anon_sym_AT,
    ACTIONS(117), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [898] = 6,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(51), 1,
      sym_great_grandchild_project_icon,
    ACTIONS(126), 1,
      anon_sym_AT,
    STATE(43), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(60), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(124), 3,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [921] = 4,
    ACTIONS(45), 1,
      anon_sym_PIPE_GT,
    STATE(56), 1,
      sym_id,
    ACTIONS(130), 3,
      sym_leaf_project_icon,
      sym_section_icon,
      anon_sym_AT,
    ACTIONS(128), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [939] = 6,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(69), 1,
      sym_grandchild_project_icon,
    ACTIONS(91), 1,
      anon_sym_AT,
    ACTIONS(89), 2,
      sym_root_project_icon,
      sym_child_project_icon,
    STATE(43), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(71), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
  [961] = 4,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(134), 2,
      sym_leaf_project_icon,
      anon_sym_AT,
    STATE(43), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    ACTIONS(132), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [979] = 4,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(95), 2,
      sym_leaf_project_icon,
      anon_sym_AT,
    STATE(43), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    ACTIONS(93), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [997] = 2,
    ACTIONS(33), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
    ACTIONS(136), 5,
      sym_leaf_project_icon,
      sym_comment_icon,
      sym_section_icon,
      anon_sym_PIPE_GT,
      anon_sym_AT,
  [1011] = 6,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(69), 1,
      sym_grandchild_project_icon,
    ACTIONS(103), 1,
      anon_sym_AT,
    ACTIONS(101), 2,
      sym_root_project_icon,
      sym_child_project_icon,
    STATE(43), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(68), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
  [1033] = 4,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(99), 2,
      sym_leaf_project_icon,
      anon_sym_AT,
    STATE(43), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    ACTIONS(97), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [1051] = 6,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(69), 1,
      sym_grandchild_project_icon,
    ACTIONS(140), 1,
      anon_sym_AT,
    ACTIONS(138), 2,
      sym_root_project_icon,
      sym_child_project_icon,
    STATE(43), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(70), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
  [1073] = 4,
    ACTIONS(146), 1,
      sym_section_icon,
    ACTIONS(144), 2,
      sym_leaf_project_icon,
      anon_sym_AT,
    STATE(43), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    ACTIONS(142), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [1091] = 6,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(83), 1,
      sym_child_project_icon,
    ACTIONS(105), 1,
      sym_root_project_icon,
    ACTIONS(107), 1,
      anon_sym_AT,
    STATE(43), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(77), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [1112] = 4,
    ACTIONS(39), 1,
      sym_leaf_project_icon,
    ACTIONS(151), 1,
      anon_sym_AT,
    STATE(49), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(149), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [1129] = 2,
    ACTIONS(153), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
    ACTIONS(155), 4,
      sym_leaf_project_icon,
      sym_comment_icon,
      sym_section_icon,
      anon_sym_AT,
  [1142] = 4,
    ACTIONS(39), 1,
      sym_leaf_project_icon,
    ACTIONS(111), 1,
      anon_sym_AT,
    STATE(49), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(109), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [1159] = 6,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(83), 1,
      sym_child_project_icon,
    ACTIONS(157), 1,
      sym_root_project_icon,
    ACTIONS(159), 1,
      anon_sym_AT,
    STATE(43), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(73), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [1180] = 4,
    ACTIONS(163), 1,
      sym_leaf_project_icon,
    ACTIONS(166), 1,
      anon_sym_AT,
    STATE(49), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(161), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [1197] = 4,
    ACTIONS(39), 1,
      sym_leaf_project_icon,
    ACTIONS(61), 1,
      anon_sym_AT,
    STATE(49), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(59), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [1214] = 6,
    ACTIONS(43), 1,
      sym_section_icon,
    ACTIONS(83), 1,
      sym_child_project_icon,
    ACTIONS(113), 1,
      sym_root_project_icon,
    ACTIONS(115), 1,
      anon_sym_AT,
    STATE(43), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(75), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [1235] = 4,
    ACTIONS(39), 1,
      sym_leaf_project_icon,
    ACTIONS(57), 1,
      anon_sym_AT,
    STATE(49), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(55), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [1252] = 2,
    ACTIONS(168), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
    ACTIONS(170), 4,
      sym_leaf_project_icon,
      sym_comment_icon,
      sym_section_icon,
      anon_sym_AT,
  [1265] = 3,
    ACTIONS(172), 1,
      aux_sym_text_line_token1,
    STATE(13), 1,
      sym_text_line,
    ACTIONS(174), 5,
      sym_escaped_left_bracket,
      sym_escaped_right_bracket,
      sym_escaped_left_parenthesis,
      sym_escaped_right_parenthesis,
      sym_escaped_at,
  [1279] = 4,
    ACTIONS(51), 1,
      sym_great_grandchild_project_icon,
    ACTIONS(126), 1,
      anon_sym_AT,
    STATE(63), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(124), 3,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [1295] = 2,
    ACTIONS(178), 3,
      sym_leaf_project_icon,
      sym_section_icon,
      anon_sym_AT,
    ACTIONS(176), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [1307] = 3,
    ACTIONS(172), 1,
      aux_sym_text_line_token1,
    STATE(7), 1,
      sym_text_line,
    ACTIONS(174), 5,
      sym_escaped_left_bracket,
      sym_escaped_right_bracket,
      sym_escaped_left_parenthesis,
      sym_escaped_right_parenthesis,
      sym_escaped_at,
  [1321] = 4,
    ACTIONS(51), 1,
      sym_great_grandchild_project_icon,
    ACTIONS(75), 1,
      anon_sym_AT,
    STATE(63), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(73), 3,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [1337] = 3,
    ACTIONS(180), 1,
      aux_sym_text_line_token1,
    STATE(82), 1,
      sym_text_line,
    ACTIONS(182), 5,
      sym_escaped_left_bracket,
      sym_escaped_right_bracket,
      sym_escaped_left_parenthesis,
      sym_escaped_right_parenthesis,
      sym_escaped_at,
  [1351] = 4,
    ACTIONS(51), 1,
      sym_great_grandchild_project_icon,
    ACTIONS(186), 1,
      anon_sym_AT,
    STATE(63), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(184), 3,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [1367] = 3,
    ACTIONS(172), 1,
      aux_sym_text_line_token1,
    STATE(16), 1,
      sym_text_line,
    ACTIONS(174), 5,
      sym_escaped_left_bracket,
      sym_escaped_right_bracket,
      sym_escaped_left_parenthesis,
      sym_escaped_right_parenthesis,
      sym_escaped_at,
  [1381] = 4,
    ACTIONS(51), 1,
      sym_great_grandchild_project_icon,
    ACTIONS(79), 1,
      anon_sym_AT,
    STATE(63), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(77), 3,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [1397] = 4,
    ACTIONS(190), 1,
      sym_great_grandchild_project_icon,
    ACTIONS(193), 1,
      anon_sym_AT,
    STATE(63), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(188), 3,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [1413] = 3,
    ACTIONS(172), 1,
      aux_sym_text_line_token1,
    STATE(8), 1,
      sym_text_line,
    ACTIONS(174), 5,
      sym_escaped_left_bracket,
      sym_escaped_right_bracket,
      sym_escaped_left_parenthesis,
      sym_escaped_right_parenthesis,
      sym_escaped_at,
  [1427] = 3,
    ACTIONS(172), 1,
      aux_sym_text_line_token1,
    STATE(35), 1,
      sym_text_line,
    ACTIONS(174), 5,
      sym_escaped_left_bracket,
      sym_escaped_right_bracket,
      sym_escaped_left_parenthesis,
      sym_escaped_right_parenthesis,
      sym_escaped_at,
  [1441] = 3,
    ACTIONS(172), 1,
      aux_sym_text_line_token1,
    STATE(11), 1,
      sym_text_line,
    ACTIONS(174), 5,
      sym_escaped_left_bracket,
      sym_escaped_right_bracket,
      sym_escaped_left_parenthesis,
      sym_escaped_right_parenthesis,
      sym_escaped_at,
  [1455] = 4,
    ACTIONS(197), 1,
      sym_grandchild_project_icon,
    ACTIONS(200), 1,
      anon_sym_AT,
    ACTIONS(195), 2,
      sym_root_project_icon,
      sym_child_project_icon,
    STATE(67), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
  [1470] = 4,
    ACTIONS(69), 1,
      sym_grandchild_project_icon,
    ACTIONS(140), 1,
      anon_sym_AT,
    ACTIONS(138), 2,
      sym_root_project_icon,
      sym_child_project_icon,
    STATE(67), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
  [1485] = 4,
    ACTIONS(69), 1,
      sym_grandchild_project_icon,
    ACTIONS(91), 1,
      anon_sym_AT,
    ACTIONS(89), 2,
      sym_root_project_icon,
      sym_child_project_icon,
    STATE(67), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
  [1500] = 4,
    ACTIONS(69), 1,
      sym_grandchild_project_icon,
    ACTIONS(204), 1,
      anon_sym_AT,
    ACTIONS(202), 2,
      sym_root_project_icon,
      sym_child_project_icon,
    STATE(67), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
  [1515] = 4,
    ACTIONS(69), 1,
      sym_grandchild_project_icon,
    ACTIONS(103), 1,
      anon_sym_AT,
    ACTIONS(101), 2,
      sym_root_project_icon,
      sym_child_project_icon,
    STATE(67), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
  [1530] = 4,
    ACTIONS(83), 1,
      sym_child_project_icon,
    ACTIONS(113), 1,
      sym_root_project_icon,
    ACTIONS(115), 1,
      anon_sym_AT,
    STATE(74), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [1544] = 4,
    ACTIONS(83), 1,
      sym_child_project_icon,
    ACTIONS(206), 1,
      sym_root_project_icon,
    ACTIONS(208), 1,
      anon_sym_AT,
    STATE(74), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [1558] = 4,
    ACTIONS(210), 1,
      sym_root_project_icon,
    ACTIONS(212), 1,
      sym_child_project_icon,
    ACTIONS(215), 1,
      anon_sym_AT,
    STATE(74), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [1572] = 4,
    ACTIONS(83), 1,
      sym_child_project_icon,
    ACTIONS(105), 1,
      sym_root_project_icon,
    ACTIONS(107), 1,
      anon_sym_AT,
    STATE(74), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [1586] = 4,
    ACTIONS(3), 1,
      sym_root_project_icon,
    ACTIONS(217), 1,
      anon_sym_AT,
    STATE(80), 1,
      sym_sync_token,
    STATE(78), 2,
      sym_root_project,
      aux_sym_source_file_repeat1,
  [1600] = 4,
    ACTIONS(83), 1,
      sym_child_project_icon,
    ACTIONS(157), 1,
      sym_root_project_icon,
    ACTIONS(159), 1,
      anon_sym_AT,
    STATE(74), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [1614] = 3,
    ACTIONS(219), 1,
      sym_root_project_icon,
    ACTIONS(222), 1,
      anon_sym_AT,
    STATE(78), 2,
      sym_root_project,
      aux_sym_source_file_repeat1,
  [1625] = 1,
    ACTIONS(224), 1,
      sym_id_number,
  [1629] = 1,
    ACTIONS(226), 1,
      ts_builtin_sym_end,
  [1633] = 1,
    ACTIONS(228), 1,
      sym_url,
  [1637] = 1,
    ACTIONS(230), 1,
      ts_builtin_sym_end,
  [1641] = 1,
    ACTIONS(232), 1,
      sym_url,
  [1645] = 1,
    ACTIONS(234), 1,
      anon_sym_LPAREN,
  [1649] = 1,
    ACTIONS(236), 1,
      anon_sym_RPAREN,
  [1653] = 1,
    ACTIONS(238), 1,
      sym_url_description,
  [1657] = 1,
    ACTIONS(240), 1,
      anon_sym_RPAREN,
  [1661] = 1,
    ACTIONS(242), 1,
      anon_sym_RBRACK,
  [1665] = 1,
    ACTIONS(136), 1,
      ts_builtin_sym_end,
  [1669] = 1,
    ACTIONS(244), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 73,
  [SMALL_STATE(5)] = 94,
  [SMALL_STATE(6)] = 115,
  [SMALL_STATE(7)] = 136,
  [SMALL_STATE(8)] = 173,
  [SMALL_STATE(9)] = 209,
  [SMALL_STATE(10)] = 240,
  [SMALL_STATE(11)] = 271,
  [SMALL_STATE(12)] = 302,
  [SMALL_STATE(13)] = 333,
  [SMALL_STATE(14)] = 368,
  [SMALL_STATE(15)] = 398,
  [SMALL_STATE(16)] = 428,
  [SMALL_STATE(17)] = 462,
  [SMALL_STATE(18)] = 492,
  [SMALL_STATE(19)] = 515,
  [SMALL_STATE(20)] = 544,
  [SMALL_STATE(21)] = 573,
  [SMALL_STATE(22)] = 598,
  [SMALL_STATE(23)] = 623,
  [SMALL_STATE(24)] = 648,
  [SMALL_STATE(25)] = 677,
  [SMALL_STATE(26)] = 701,
  [SMALL_STATE(27)] = 729,
  [SMALL_STATE(28)] = 753,
  [SMALL_STATE(29)] = 777,
  [SMALL_STATE(30)] = 805,
  [SMALL_STATE(31)] = 833,
  [SMALL_STATE(32)] = 856,
  [SMALL_STATE(33)] = 879,
  [SMALL_STATE(34)] = 898,
  [SMALL_STATE(35)] = 921,
  [SMALL_STATE(36)] = 939,
  [SMALL_STATE(37)] = 961,
  [SMALL_STATE(38)] = 979,
  [SMALL_STATE(39)] = 997,
  [SMALL_STATE(40)] = 1011,
  [SMALL_STATE(41)] = 1033,
  [SMALL_STATE(42)] = 1051,
  [SMALL_STATE(43)] = 1073,
  [SMALL_STATE(44)] = 1091,
  [SMALL_STATE(45)] = 1112,
  [SMALL_STATE(46)] = 1129,
  [SMALL_STATE(47)] = 1142,
  [SMALL_STATE(48)] = 1159,
  [SMALL_STATE(49)] = 1180,
  [SMALL_STATE(50)] = 1197,
  [SMALL_STATE(51)] = 1214,
  [SMALL_STATE(52)] = 1235,
  [SMALL_STATE(53)] = 1252,
  [SMALL_STATE(54)] = 1265,
  [SMALL_STATE(55)] = 1279,
  [SMALL_STATE(56)] = 1295,
  [SMALL_STATE(57)] = 1307,
  [SMALL_STATE(58)] = 1321,
  [SMALL_STATE(59)] = 1337,
  [SMALL_STATE(60)] = 1351,
  [SMALL_STATE(61)] = 1367,
  [SMALL_STATE(62)] = 1381,
  [SMALL_STATE(63)] = 1397,
  [SMALL_STATE(64)] = 1413,
  [SMALL_STATE(65)] = 1427,
  [SMALL_STATE(66)] = 1441,
  [SMALL_STATE(67)] = 1455,
  [SMALL_STATE(68)] = 1470,
  [SMALL_STATE(69)] = 1485,
  [SMALL_STATE(70)] = 1500,
  [SMALL_STATE(71)] = 1515,
  [SMALL_STATE(72)] = 1530,
  [SMALL_STATE(73)] = 1544,
  [SMALL_STATE(74)] = 1558,
  [SMALL_STATE(75)] = 1572,
  [SMALL_STATE(76)] = 1586,
  [SMALL_STATE(77)] = 1600,
  [SMALL_STATE(78)] = 1614,
  [SMALL_STATE(79)] = 1625,
  [SMALL_STATE(80)] = 1629,
  [SMALL_STATE(81)] = 1633,
  [SMALL_STATE(82)] = 1637,
  [SMALL_STATE(83)] = 1641,
  [SMALL_STATE(84)] = 1645,
  [SMALL_STATE(85)] = 1649,
  [SMALL_STATE(86)] = 1653,
  [SMALL_STATE(87)] = 1657,
  [SMALL_STATE(88)] = 1661,
  [SMALL_STATE(89)] = 1665,
  [SMALL_STATE(90)] = 1669,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(3),
  [20] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(86),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(83),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(5),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_url, 6),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text_line, 1),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_url, 3),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_great_grandchild_project, 2),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 2),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grandchild_project, 2),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 2),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_great_grandchild_project, 3),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 3),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_great_grandchild_project, 4),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 4),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_project, 2),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_project, 2),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child_project, 2),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 2),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grandchild_project, 3),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 3),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grandchild_project, 4),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 4),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_root_project, 2),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_project, 2),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child_project, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 3),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_project, 4),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_project, 4),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_project, 3),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_project, 3),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child_project, 4),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 4),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_root_project, 4),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_project, 4),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_great_grandchild_project, 5),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 5),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_root_project, 3),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_project, 3),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_root_project_repeat1, 2),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_root_project_repeat1, 2),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_root_project_repeat1, 2), SHIFT_REPEAT(18),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grandchild_project, 5),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 5),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 2),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_project, 5),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_project, 5),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_line, 1),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child_project, 5),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 5),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_root_project_repeat2, 2),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_root_project_repeat2, 2),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_root_project_repeat2, 2), SHIFT_REPEAT(65),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_great_grandchild_project, 6),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 6),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_root_project, 5),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_project, 5),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2), SHIFT_REPEAT(66),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_id, 2),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id, 2),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 3),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grandchild_project, 6),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 6),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_grandchild_project_repeat1, 2),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grandchild_project_repeat1, 2), SHIFT_REPEAT(57),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_grandchild_project_repeat1, 2),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_child_project_repeat1, 2),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_child_project_repeat1, 2), SHIFT_REPEAT(64),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_child_project_repeat1, 2),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child_project, 6),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 6),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_root_project, 6),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_project, 6),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_root_project_repeat3, 2),
  [212] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_root_project_repeat3, 2), SHIFT_REPEAT(54),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_root_project_repeat3, 2),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [219] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(61),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sync_token, 2),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [244] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_projects(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
