#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 71
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  sym_root_project_icon = 2,
  sym_child_project_icon = 3,
  sym_grandchild_project_icon = 4,
  sym_great_grandchild_project_icon = 5,
  sym_leaf_project_icon = 6,
  sym_comment_icon = 7,
  sym_section_icon = 8,
  anon_sym_PIPE_GT = 9,
  anon_sym_AT = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  sym_url = 15,
  sym_description = 16,
  sym_id_number = 17,
  sym_text_line = 18,
  sym_source_file = 19,
  sym_root_project = 20,
  sym_child_project = 21,
  sym_grandchild_project = 22,
  sym_great_grandchild_project = 23,
  sym_leaf_project = 24,
  sym_comment = 25,
  sym_section = 26,
  sym_id = 27,
  sym_sync_token = 28,
  sym_markdown_url = 29,
  aux_sym_source_file_repeat1 = 30,
  aux_sym_root_project_repeat1 = 31,
  aux_sym_root_project_repeat2 = 32,
  aux_sym_root_project_repeat3 = 33,
  aux_sym_child_project_repeat1 = 34,
  aux_sym_grandchild_project_repeat1 = 35,
  aux_sym_great_grandchild_project_repeat1 = 36,
  aux_sym_comment_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym_root_project_icon] = "root_project_icon",
  [sym_child_project_icon] = "child_project_icon",
  [sym_grandchild_project_icon] = "grandchild_project_icon",
  [sym_great_grandchild_project_icon] = "great_grandchild_project_icon",
  [sym_leaf_project_icon] = "leaf_project_icon",
  [sym_comment_icon] = "comment_icon",
  [sym_section_icon] = "section_icon",
  [anon_sym_PIPE_GT] = "|>",
  [anon_sym_AT] = "@",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_url] = "url",
  [sym_description] = "description",
  [sym_id_number] = "id_number",
  [sym_text_line] = "text_line",
  [sym_source_file] = "source_file",
  [sym_root_project] = "root_project",
  [sym_child_project] = "child_project",
  [sym_grandchild_project] = "grandchild_project",
  [sym_great_grandchild_project] = "great_grandchild_project",
  [sym_leaf_project] = "leaf_project",
  [sym_comment] = "comment",
  [sym_section] = "section",
  [sym_id] = "id",
  [sym_sync_token] = "sync_token",
  [sym_markdown_url] = "markdown_url",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_root_project_repeat1] = "root_project_repeat1",
  [aux_sym_root_project_repeat2] = "root_project_repeat2",
  [aux_sym_root_project_repeat3] = "root_project_repeat3",
  [aux_sym_child_project_repeat1] = "child_project_repeat1",
  [aux_sym_grandchild_project_repeat1] = "grandchild_project_repeat1",
  [aux_sym_great_grandchild_project_repeat1] = "great_grandchild_project_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym_root_project_icon] = sym_root_project_icon,
  [sym_child_project_icon] = sym_child_project_icon,
  [sym_grandchild_project_icon] = sym_grandchild_project_icon,
  [sym_great_grandchild_project_icon] = sym_great_grandchild_project_icon,
  [sym_leaf_project_icon] = sym_leaf_project_icon,
  [sym_comment_icon] = sym_comment_icon,
  [sym_section_icon] = sym_section_icon,
  [anon_sym_PIPE_GT] = anon_sym_PIPE_GT,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_url] = sym_url,
  [sym_description] = sym_description,
  [sym_id_number] = sym_id_number,
  [sym_text_line] = sym_text_line,
  [sym_source_file] = sym_source_file,
  [sym_root_project] = sym_root_project,
  [sym_child_project] = sym_child_project,
  [sym_grandchild_project] = sym_grandchild_project,
  [sym_great_grandchild_project] = sym_great_grandchild_project,
  [sym_leaf_project] = sym_leaf_project,
  [sym_comment] = sym_comment,
  [sym_section] = sym_section,
  [sym_id] = sym_id,
  [sym_sync_token] = sym_sync_token,
  [sym_markdown_url] = sym_markdown_url,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_root_project_repeat1] = aux_sym_root_project_repeat1,
  [aux_sym_root_project_repeat2] = aux_sym_root_project_repeat2,
  [aux_sym_root_project_repeat3] = aux_sym_root_project_repeat3,
  [aux_sym_child_project_repeat1] = aux_sym_child_project_repeat1,
  [aux_sym_grandchild_project_repeat1] = aux_sym_grandchild_project_repeat1,
  [aux_sym_great_grandchild_project_repeat1] = aux_sym_great_grandchild_project_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_root_project_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_child_project_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_grandchild_project_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_great_grandchild_project_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_project_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_section_icon] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_url] = {
    .visible = true,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [sym_id_number] = {
    .visible = true,
    .named = true,
  },
  [sym_text_line] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_root_project] = {
    .visible = true,
    .named = true,
  },
  [sym_child_project] = {
    .visible = true,
    .named = true,
  },
  [sym_grandchild_project] = {
    .visible = true,
    .named = true,
  },
  [sym_great_grandchild_project] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_project] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym_sync_token] = {
    .visible = true,
    .named = true,
  },
  [sym_markdown_url] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_root_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_root_project_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_root_project_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_child_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_grandchild_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_great_grandchild_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
};

static inline bool sym_text_line_character_set_1(int32_t c) {
  return (c < '('
    ? (c < '#'
      ? (c < '\n'
        ? c == 0
        : c <= '\n')
      : (c <= '#' || c == '&'))
    : (c <= '(' || (c < '['
      ? (c < '>'
        ? c == '+'
        : c <= '>')
      : (c <= '[' || c == '|'))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '&') ADVANCE(22);
      if (lookahead == '(') ADVANCE(27);
      if (lookahead == ')') ADVANCE(28);
      if (lookahead == '+') ADVANCE(21);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == ']') ADVANCE(26);
      if (lookahead == 'h') ADVANCE(10);
      if (lookahead == '|') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '(') ADVANCE(27);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == '|') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '&' &&
          lookahead != '+' &&
          lookahead != '>') ADVANCE(35);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2)
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '&' &&
          lookahead != '(' &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '[' &&
          lookahead != '|') ADVANCE(35);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(4);
      if (lookahead == 's') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == 'p') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 11:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(31);
      END_STATE();
    case 12:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != '$' &&
          lookahead != '.' &&
          lookahead != '/' &&
          lookahead != '?' &&
          lookahead != ']') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_root_project_icon);
      if (lookahead == '#') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_child_project_icon);
      if (lookahead == '#') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_grandchild_project_icon);
      if (lookahead == '#') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_great_grandchild_project_icon);
      if (lookahead == '#') ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_leaf_project_icon);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_comment_icon);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_section_icon);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_PIPE_GT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_url);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ']') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_description);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_description);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_id_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '&' &&
          lookahead != '(' &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '[' &&
          lookahead != '|') ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\t' ||
          (11 <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (!sym_text_line_character_set_1(lookahead)) ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_text_line);
      if (!sym_text_line_character_set_1(lookahead)) ADVANCE(35);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 11},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_root_project_icon] = ACTIONS(1),
    [sym_child_project_icon] = ACTIONS(1),
    [sym_grandchild_project_icon] = ACTIONS(1),
    [sym_great_grandchild_project_icon] = ACTIONS(1),
    [sym_leaf_project_icon] = ACTIONS(1),
    [sym_comment_icon] = ACTIONS(1),
    [sym_section_icon] = ACTIONS(1),
    [anon_sym_PIPE_GT] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_url] = ACTIONS(1),
    [sym_id_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(70),
    [sym_root_project] = STATE(42),
    [aux_sym_source_file_repeat1] = STATE(42),
    [sym_root_project_icon] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(7), 1,
      sym_leaf_project_icon,
    ACTIONS(9), 1,
      sym_comment_icon,
    ACTIONS(11), 1,
      sym_section_icon,
    ACTIONS(13), 1,
      anon_sym_AT,
    STATE(3), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(11), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(27), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(5), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [31] = 8,
    ACTIONS(7), 1,
      sym_leaf_project_icon,
    ACTIONS(9), 1,
      sym_comment_icon,
    ACTIONS(11), 1,
      sym_section_icon,
    ACTIONS(17), 1,
      anon_sym_AT,
    STATE(12), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(16), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(28), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(15), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [62] = 8,
    ACTIONS(9), 1,
      sym_comment_icon,
    ACTIONS(11), 1,
      sym_section_icon,
    ACTIONS(21), 1,
      sym_great_grandchild_project_icon,
    ACTIONS(23), 1,
      anon_sym_AT,
    STATE(14), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(16), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(32), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(19), 3,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [92] = 8,
    ACTIONS(9), 1,
      sym_comment_icon,
    ACTIONS(11), 1,
      sym_section_icon,
    ACTIONS(21), 1,
      sym_great_grandchild_project_icon,
    ACTIONS(27), 1,
      anon_sym_AT,
    STATE(4), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(15), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(30), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(25), 3,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [122] = 8,
    ACTIONS(9), 1,
      sym_comment_icon,
    ACTIONS(11), 1,
      sym_section_icon,
    ACTIONS(31), 1,
      sym_grandchild_project_icon,
    ACTIONS(33), 1,
      anon_sym_AT,
    ACTIONS(29), 2,
      sym_root_project_icon,
      sym_child_project_icon,
    STATE(9), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(18), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(38), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
  [151] = 6,
    ACTIONS(9), 1,
      sym_comment_icon,
    ACTIONS(11), 1,
      sym_section_icon,
    ACTIONS(37), 2,
      sym_leaf_project_icon,
      anon_sym_AT,
    STATE(16), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(17), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    ACTIONS(35), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [176] = 6,
    ACTIONS(9), 1,
      sym_comment_icon,
    ACTIONS(11), 1,
      sym_section_icon,
    ACTIONS(41), 2,
      sym_leaf_project_icon,
      anon_sym_AT,
    STATE(7), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(20), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    ACTIONS(39), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [201] = 8,
    ACTIONS(9), 1,
      sym_comment_icon,
    ACTIONS(11), 1,
      sym_section_icon,
    ACTIONS(31), 1,
      sym_grandchild_project_icon,
    ACTIONS(45), 1,
      anon_sym_AT,
    ACTIONS(43), 2,
      sym_root_project_icon,
      sym_child_project_icon,
    STATE(16), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(19), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(39), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
  [230] = 8,
    ACTIONS(9), 1,
      sym_comment_icon,
    ACTIONS(11), 1,
      sym_section_icon,
    ACTIONS(47), 1,
      sym_root_project_icon,
    ACTIONS(49), 1,
      sym_child_project_icon,
    ACTIONS(51), 1,
      anon_sym_AT,
    STATE(13), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(25), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(47), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [258] = 6,
    ACTIONS(7), 1,
      sym_leaf_project_icon,
    ACTIONS(11), 1,
      sym_section_icon,
    ACTIONS(17), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(28), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(15), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [282] = 6,
    ACTIONS(7), 1,
      sym_leaf_project_icon,
    ACTIONS(11), 1,
      sym_section_icon,
    ACTIONS(55), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(23), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(53), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [306] = 8,
    ACTIONS(9), 1,
      sym_comment_icon,
    ACTIONS(11), 1,
      sym_section_icon,
    ACTIONS(49), 1,
      sym_child_project_icon,
    ACTIONS(57), 1,
      sym_root_project_icon,
    ACTIONS(59), 1,
      anon_sym_AT,
    STATE(16), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    STATE(24), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(46), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [334] = 6,
    ACTIONS(11), 1,
      sym_section_icon,
    ACTIONS(21), 1,
      sym_great_grandchild_project_icon,
    ACTIONS(63), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(34), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(61), 3,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [357] = 6,
    ACTIONS(11), 1,
      sym_section_icon,
    ACTIONS(21), 1,
      sym_great_grandchild_project_icon,
    ACTIONS(23), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(32), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(19), 3,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [380] = 4,
    ACTIONS(69), 1,
      sym_comment_icon,
    STATE(16), 2,
      sym_comment,
      aux_sym_root_project_repeat1,
    ACTIONS(67), 3,
      sym_leaf_project_icon,
      sym_section_icon,
      anon_sym_AT,
    ACTIONS(65), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [399] = 4,
    ACTIONS(11), 1,
      sym_section_icon,
    ACTIONS(74), 2,
      sym_leaf_project_icon,
      anon_sym_AT,
    STATE(21), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    ACTIONS(72), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [417] = 6,
    ACTIONS(11), 1,
      sym_section_icon,
    ACTIONS(31), 1,
      sym_grandchild_project_icon,
    ACTIONS(45), 1,
      anon_sym_AT,
    ACTIONS(43), 2,
      sym_root_project_icon,
      sym_child_project_icon,
    STATE(21), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(39), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
  [439] = 6,
    ACTIONS(11), 1,
      sym_section_icon,
    ACTIONS(31), 1,
      sym_grandchild_project_icon,
    ACTIONS(78), 1,
      anon_sym_AT,
    ACTIONS(76), 2,
      sym_root_project_icon,
      sym_child_project_icon,
    STATE(21), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(37), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
  [461] = 4,
    ACTIONS(11), 1,
      sym_section_icon,
    ACTIONS(37), 2,
      sym_leaf_project_icon,
      anon_sym_AT,
    STATE(21), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    ACTIONS(35), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [479] = 4,
    ACTIONS(84), 1,
      sym_section_icon,
    ACTIONS(82), 2,
      sym_leaf_project_icon,
      anon_sym_AT,
    STATE(21), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    ACTIONS(80), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [497] = 2,
    ACTIONS(87), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
    ACTIONS(89), 4,
      sym_leaf_project_icon,
      sym_comment_icon,
      sym_section_icon,
      anon_sym_AT,
  [510] = 4,
    ACTIONS(7), 1,
      sym_leaf_project_icon,
    ACTIONS(93), 1,
      anon_sym_AT,
    STATE(29), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(91), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [527] = 6,
    ACTIONS(11), 1,
      sym_section_icon,
    ACTIONS(49), 1,
      sym_child_project_icon,
    ACTIONS(95), 1,
      sym_root_project_icon,
    ACTIONS(97), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(41), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [548] = 6,
    ACTIONS(11), 1,
      sym_section_icon,
    ACTIONS(49), 1,
      sym_child_project_icon,
    ACTIONS(57), 1,
      sym_root_project_icon,
    ACTIONS(59), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_section,
      aux_sym_root_project_repeat2,
    STATE(46), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [569] = 2,
    ACTIONS(99), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
    ACTIONS(101), 4,
      sym_leaf_project_icon,
      sym_comment_icon,
      sym_section_icon,
      anon_sym_AT,
  [582] = 4,
    ACTIONS(7), 1,
      sym_leaf_project_icon,
    ACTIONS(17), 1,
      anon_sym_AT,
    STATE(29), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(15), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [599] = 4,
    ACTIONS(7), 1,
      sym_leaf_project_icon,
    ACTIONS(55), 1,
      anon_sym_AT,
    STATE(29), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(53), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [616] = 4,
    ACTIONS(105), 1,
      sym_leaf_project_icon,
    ACTIONS(108), 1,
      anon_sym_AT,
    STATE(29), 2,
      sym_leaf_project,
      aux_sym_great_grandchild_project_repeat1,
    ACTIONS(103), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [633] = 4,
    ACTIONS(21), 1,
      sym_great_grandchild_project_icon,
    ACTIONS(23), 1,
      anon_sym_AT,
    STATE(33), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(19), 3,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [649] = 5,
    ACTIONS(112), 1,
      anon_sym_PIPE_GT,
    ACTIONS(114), 1,
      anon_sym_LBRACK,
    STATE(22), 1,
      sym_id,
    ACTIONS(110), 2,
      anon_sym_LF,
      sym_text_line,
    STATE(36), 2,
      sym_markdown_url,
      aux_sym_comment_repeat1,
  [667] = 4,
    ACTIONS(21), 1,
      sym_great_grandchild_project_icon,
    ACTIONS(63), 1,
      anon_sym_AT,
    STATE(33), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(61), 3,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [683] = 4,
    ACTIONS(118), 1,
      sym_great_grandchild_project_icon,
    ACTIONS(121), 1,
      anon_sym_AT,
    STATE(33), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(116), 3,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [699] = 4,
    ACTIONS(21), 1,
      sym_great_grandchild_project_icon,
    ACTIONS(125), 1,
      anon_sym_AT,
    STATE(33), 2,
      sym_great_grandchild_project,
      aux_sym_grandchild_project_repeat1,
    ACTIONS(123), 3,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
  [715] = 2,
    ACTIONS(129), 3,
      sym_leaf_project_icon,
      sym_section_icon,
      anon_sym_AT,
    ACTIONS(127), 4,
      sym_root_project_icon,
      sym_child_project_icon,
      sym_grandchild_project_icon,
      sym_great_grandchild_project_icon,
  [727] = 4,
    ACTIONS(134), 1,
      anon_sym_PIPE_GT,
    ACTIONS(136), 1,
      anon_sym_LBRACK,
    ACTIONS(131), 2,
      anon_sym_LF,
      sym_text_line,
    STATE(36), 2,
      sym_markdown_url,
      aux_sym_comment_repeat1,
  [742] = 4,
    ACTIONS(31), 1,
      sym_grandchild_project_icon,
    ACTIONS(141), 1,
      anon_sym_AT,
    ACTIONS(139), 2,
      sym_root_project_icon,
      sym_child_project_icon,
    STATE(40), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
  [757] = 4,
    ACTIONS(31), 1,
      sym_grandchild_project_icon,
    ACTIONS(45), 1,
      anon_sym_AT,
    ACTIONS(43), 2,
      sym_root_project_icon,
      sym_child_project_icon,
    STATE(40), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
  [772] = 4,
    ACTIONS(31), 1,
      sym_grandchild_project_icon,
    ACTIONS(78), 1,
      anon_sym_AT,
    ACTIONS(76), 2,
      sym_root_project_icon,
      sym_child_project_icon,
    STATE(40), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
  [787] = 4,
    ACTIONS(145), 1,
      sym_grandchild_project_icon,
    ACTIONS(148), 1,
      anon_sym_AT,
    ACTIONS(143), 2,
      sym_root_project_icon,
      sym_child_project_icon,
    STATE(40), 2,
      sym_grandchild_project,
      aux_sym_child_project_repeat1,
  [802] = 4,
    ACTIONS(49), 1,
      sym_child_project_icon,
    ACTIONS(150), 1,
      sym_root_project_icon,
    ACTIONS(152), 1,
      anon_sym_AT,
    STATE(45), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [816] = 4,
    ACTIONS(3), 1,
      sym_root_project_icon,
    ACTIONS(154), 1,
      anon_sym_AT,
    STATE(66), 1,
      sym_sync_token,
    STATE(48), 2,
      sym_root_project,
      aux_sym_source_file_repeat1,
  [830] = 3,
    ACTIONS(114), 1,
      anon_sym_LBRACK,
    ACTIONS(156), 2,
      anon_sym_LF,
      sym_text_line,
    STATE(31), 2,
      sym_markdown_url,
      aux_sym_comment_repeat1,
  [842] = 2,
    ACTIONS(160), 1,
      anon_sym_LPAREN,
    ACTIONS(158), 4,
      anon_sym_LF,
      anon_sym_PIPE_GT,
      anon_sym_LBRACK,
      sym_text_line,
  [852] = 4,
    ACTIONS(162), 1,
      sym_root_project_icon,
    ACTIONS(164), 1,
      sym_child_project_icon,
    ACTIONS(167), 1,
      anon_sym_AT,
    STATE(45), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [866] = 4,
    ACTIONS(49), 1,
      sym_child_project_icon,
    ACTIONS(95), 1,
      sym_root_project_icon,
    ACTIONS(97), 1,
      anon_sym_AT,
    STATE(45), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [880] = 4,
    ACTIONS(49), 1,
      sym_child_project_icon,
    ACTIONS(57), 1,
      sym_root_project_icon,
    ACTIONS(59), 1,
      anon_sym_AT,
    STATE(45), 2,
      sym_child_project,
      aux_sym_root_project_repeat3,
  [894] = 3,
    ACTIONS(169), 1,
      sym_root_project_icon,
    ACTIONS(172), 1,
      anon_sym_AT,
    STATE(48), 2,
      sym_root_project,
      aux_sym_source_file_repeat1,
  [905] = 1,
    ACTIONS(174), 4,
      anon_sym_LF,
      anon_sym_PIPE_GT,
      anon_sym_LBRACK,
      sym_text_line,
  [912] = 2,
    ACTIONS(176), 1,
      anon_sym_PIPE_GT,
    STATE(6), 1,
      sym_id,
  [919] = 2,
    ACTIONS(176), 1,
      anon_sym_PIPE_GT,
    STATE(5), 1,
      sym_id,
  [926] = 2,
    ACTIONS(176), 1,
      anon_sym_PIPE_GT,
    STATE(10), 1,
      sym_id,
  [933] = 2,
    ACTIONS(176), 1,
      anon_sym_PIPE_GT,
    STATE(8), 1,
      sym_id,
  [940] = 2,
    ACTIONS(176), 1,
      anon_sym_PIPE_GT,
    STATE(2), 1,
      sym_id,
  [947] = 2,
    ACTIONS(176), 1,
      anon_sym_PIPE_GT,
    STATE(35), 1,
      sym_id,
  [954] = 1,
    ACTIONS(178), 1,
      anon_sym_RBRACK,
  [958] = 1,
    ACTIONS(180), 1,
      sym_description,
  [962] = 1,
    ACTIONS(182), 1,
      sym_text_line,
  [966] = 1,
    ACTIONS(184), 1,
      sym_text_line,
  [970] = 1,
    ACTIONS(186), 1,
      sym_url,
  [974] = 1,
    ACTIONS(188), 1,
      sym_text_line,
  [978] = 1,
    ACTIONS(190), 1,
      sym_text_line,
  [982] = 1,
    ACTIONS(192), 1,
      ts_builtin_sym_end,
  [986] = 1,
    ACTIONS(194), 1,
      sym_id_number,
  [990] = 1,
    ACTIONS(196), 1,
      sym_text_line,
  [994] = 1,
    ACTIONS(198), 1,
      ts_builtin_sym_end,
  [998] = 1,
    ACTIONS(200), 1,
      sym_text_line,
  [1002] = 1,
    ACTIONS(202), 1,
      anon_sym_RPAREN,
  [1006] = 1,
    ACTIONS(204), 1,
      sym_text_line,
  [1010] = 1,
    ACTIONS(206), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 92,
  [SMALL_STATE(6)] = 122,
  [SMALL_STATE(7)] = 151,
  [SMALL_STATE(8)] = 176,
  [SMALL_STATE(9)] = 201,
  [SMALL_STATE(10)] = 230,
  [SMALL_STATE(11)] = 258,
  [SMALL_STATE(12)] = 282,
  [SMALL_STATE(13)] = 306,
  [SMALL_STATE(14)] = 334,
  [SMALL_STATE(15)] = 357,
  [SMALL_STATE(16)] = 380,
  [SMALL_STATE(17)] = 399,
  [SMALL_STATE(18)] = 417,
  [SMALL_STATE(19)] = 439,
  [SMALL_STATE(20)] = 461,
  [SMALL_STATE(21)] = 479,
  [SMALL_STATE(22)] = 497,
  [SMALL_STATE(23)] = 510,
  [SMALL_STATE(24)] = 527,
  [SMALL_STATE(25)] = 548,
  [SMALL_STATE(26)] = 569,
  [SMALL_STATE(27)] = 582,
  [SMALL_STATE(28)] = 599,
  [SMALL_STATE(29)] = 616,
  [SMALL_STATE(30)] = 633,
  [SMALL_STATE(31)] = 649,
  [SMALL_STATE(32)] = 667,
  [SMALL_STATE(33)] = 683,
  [SMALL_STATE(34)] = 699,
  [SMALL_STATE(35)] = 715,
  [SMALL_STATE(36)] = 727,
  [SMALL_STATE(37)] = 742,
  [SMALL_STATE(38)] = 757,
  [SMALL_STATE(39)] = 772,
  [SMALL_STATE(40)] = 787,
  [SMALL_STATE(41)] = 802,
  [SMALL_STATE(42)] = 816,
  [SMALL_STATE(43)] = 830,
  [SMALL_STATE(44)] = 842,
  [SMALL_STATE(45)] = 852,
  [SMALL_STATE(46)] = 866,
  [SMALL_STATE(47)] = 880,
  [SMALL_STATE(48)] = 894,
  [SMALL_STATE(49)] = 905,
  [SMALL_STATE(50)] = 912,
  [SMALL_STATE(51)] = 919,
  [SMALL_STATE(52)] = 926,
  [SMALL_STATE(53)] = 933,
  [SMALL_STATE(54)] = 940,
  [SMALL_STATE(55)] = 947,
  [SMALL_STATE(56)] = 954,
  [SMALL_STATE(57)] = 958,
  [SMALL_STATE(58)] = 962,
  [SMALL_STATE(59)] = 966,
  [SMALL_STATE(60)] = 970,
  [SMALL_STATE(61)] = 974,
  [SMALL_STATE(62)] = 978,
  [SMALL_STATE(63)] = 982,
  [SMALL_STATE(64)] = 986,
  [SMALL_STATE(65)] = 990,
  [SMALL_STATE(66)] = 994,
  [SMALL_STATE(67)] = 998,
  [SMALL_STATE(68)] = 1002,
  [SMALL_STATE(69)] = 1006,
  [SMALL_STATE(70)] = 1010,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [5] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_great_grandchild_project, 3),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 3),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_great_grandchild_project, 4),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 4),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grandchild_project, 4),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 4),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grandchild_project, 3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 3),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child_project, 3),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 3),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_project, 4),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_project, 4),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_project, 3),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_project, 3),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child_project, 4),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 4),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_root_project, 3),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_project, 3),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_great_grandchild_project, 5),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 5),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_root_project, 4),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_project, 4),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grandchild_project, 5),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 5),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_root_project_repeat1, 2),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_root_project_repeat1, 2),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_root_project_repeat1, 2), SHIFT_REPEAT(43),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_project, 5),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_project, 5),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child_project, 5),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 5),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_root_project_repeat2, 2),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_root_project_repeat2, 2),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_root_project_repeat2, 2), SHIFT_REPEAT(59),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_great_grandchild_project, 6),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 6),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_root_project, 5),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_project, 5),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_id, 2),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id, 2),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2), SHIFT_REPEAT(58),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_grandchild_project_repeat1, 2),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grandchild_project_repeat1, 2), SHIFT_REPEAT(65),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_grandchild_project_repeat1, 2),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grandchild_project, 6),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 6),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 3),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3),
  [131] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(36),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2),
  [136] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(60),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child_project, 6),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 6),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_child_project_repeat1, 2),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_child_project_repeat1, 2), SHIFT_REPEAT(62),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_child_project_repeat1, 2),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_root_project, 6),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_project, 6),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_url, 3),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_root_project_repeat3, 2),
  [164] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_root_project_repeat3, 2), SHIFT_REPEAT(61),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_root_project_repeat3, 2),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(69),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_url, 6),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sync_token, 2),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [206] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_projects(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
